fruits=frozenset(["apple","banana","mango"])
print("frozen set:",fruits)
tropical=frozenset(["banana","guvava"])
all_fruits=fruits.union(tropical)
print("union:",all_fruits)
common_fruits=fruits.intersection(tropical)
print("common fruits:",common_fruits)
only_fruits=fruits.difference(tropical)
print("difference:",only_fruits)
